---
- name: Download and install the latest version of dust
  become: yes
  tasks:
    - name: Get the latest release version of dust from GitHub
      uri:
        url: "https://api.github.com/repos/bootandy/dust/releases/latest"
        return_content: yes
        headers:
          Accept: "application/vnd.github.v3+json"
      register: release_info

    - name: Extract dust version from GitHub release
      set_fact:
        dust_version: "{{ release_info.json.tag_name }}"

    - name: Download the dust binary tarball
      get_url:
        url: "https://github.com/bootandy/dust/releases/download/{{ dust_version }}/dust-{{ dust_version }}-x86_64-unknown-linux-musl.tar.gz"
        dest: "/tmp/dust-{{ dust_version }}.tar.gz"

    - name: Extract the tarball
      unarchive:
        src: "/tmp/dust-{{ dust_version }}.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    - name: Move the dust binary to /usr/bin
      command: mv /tmp/dust-{{ dust_version }}/dust /usr/bin/dust
      creates: /usr/bin/dust

    - name: Clean up the tarball and extracted files
      file:
        path: "/tmp/dust-{{ dust_version }}.tar.gz"
        state: absent
