---
- name: Install Act
  hosts: localhost
  tasks:
    - name: Download Act install script
      get_url:
        url: https://raw.githubusercontent.com/nektos/act/master/install.sh
        dest: /tmp/act-install.sh
        mode: '0755'

    - name: Run Act install script
      command: sh /tmp/act-install.sh

    - name: Remove Act install script
      file:
        path: /tmp/act-install.sh
        state: absent
