---
- name: Install required basic packages
  become: true
  ansible.builtin.apt:
    name:
      - zsh
      - nano
      - eza
      - git
      - fzf
      - github-cli
      - dust
      - zsh-autosuggestions
      - ca-certificates
      - curl
      - vim
      - ufw
      - fail2ban
      - jq
      - clang
      - g++
      - build-essential
    state: present
    update_cache: true
