---
- name: Check if Starship is installed using which
  command: which starship
  register: starship_installed
  ignore_errors: true

- name: Download Starship install script
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship-install.sh
    mode: '0755'
  when: starship_installed.rc != 0

- name: Run Starship install script
  command: sh /tmp/starship-install.sh -y
  when: starship_installed.rc != 0

- name: Remove Starship install script
  file:
    path: /tmp/starship-install.sh
    state: absent
  when: starship_installed.rc != 0
