---
- name: Check if Docker is installed using which
  command: which docker
  register: docker_installed
  ignore_errors: true

- name: Set architecture fact for Docker
  set_fact:
    arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"
  when: docker_installed.rc != 0

- name: Setup Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  when: docker_installed.rc != 0

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker.list
  when: docker_installed.rc != 0

- name: Update apt cache after adding Docker repo
  apt:
    update_cache: yes
  when: docker_installed.rc != 0

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add user to Docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes