---
- name: Run all playbooks
  hosts: localhost
  gather_facts: true

  vars_prompt:
    - name: "tailscale_authkey"
      prompt: "Please enter your Tailscale authkey"
      private: true

  tasks:
    - name: Install Packages
      include_tasks: packages/install_packages.yml
    
    - name: Install Dust
      include_tasks: 
        file: packages/install_dust.yml
        apply:
          become: true

    - name: Install Starship
      include_tasks: 
        file: packages/install_starship.yml

    - name: Install Oh My Zsh
      include_tasks: 
        file: packages/install_ohmyzsh.yml

    - name: Install Atuin
      include_tasks: 
        file: packages/install_atuin.yml

    - name: Install Act
      include_tasks: 
        file: packages/install_act.yml

    - name: Setup Docker repository and install Docker packages
      include_tasks: 
        file: packages/setup_docker.yml
        apply:
          become: true

    - name: Setup Tailscale repository and install Tailscale package
      include_tasks: 
        file: packages/setup_tailscale.yml
        apply:
          become: true

    - name: Symlink dotfiles
      include_tasks: 
        file: dotfiles/symlink_dotfiles.yml
