---
- name: Symlink .zshrc to home directory
  ansible.builtin.file:
    src: "{{ playbook_dir }}/../.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: yes

- name: Symlink starship.toml to home directory
  ansible.builtin.file:
    src: "{{ playbook_dir }}/../.config/starship.toml"
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    state: link
    force: yes

- name: Symlink aliases to home directory
  ansible.builtin.file:
    src: "{{ playbook_dir }}/../.zsh/aliases.zsh"
    dest: "{{ ansible_env.HOME }}/.zsh/aliases.zsh"
    state: link
    force: yes