---
- name: Symlink .zshrc to home directory
  ansible.builtin.file:
    src: "{{ playbook_dir }}/../.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: yes

- name: Symlink .config to home directory
  ansible.builtin.file:
    src: "{{ playbook_dir }}/../.config"
    dest: "{{ ansible_env.HOME }}/.config"
    state: link
    force: yes
